### PR TITLE
test: disable dot-imports check for ginkgo and omega

### PR DESCRIPTION
**Pull request by artek-koltun**
This is needed due to update `golangci-lint `
https://github.com/opiproject/godpu/pull/344
https://github.com/opiproject/godpu/pull/345
https://github.com/opiproject/godpu/pull/346

@brianroch since you are the main author of this test code, do you prefer to use `nolint` section over dot imports or rework to prepend all the cases with package names

### CODE REVIEW

**Comment by artek-koltun** [comment]
need to bring up redis instance for evpn after https://github.com/opiproject/opi-evpn-bridge/pull/266/files

**Comment by glimchb** [comment]
@brianroch see annotations in https://github.com/opiproject/godpu/pull/344/files
or failure of CI https://github.com/opiproject/godpu/actions/runs/6593888304/job/17917049018?pr=344
```
  Running [/home/runner/golangci-lint-1.55.0-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=.] in [/home/runner/work/godpu/godpu] ...
  Warning: dot-imports: should not use dot imports (revive)
  Warning: dot-imports: should not use dot imports (revive)
  Warning: dot-imports: should not use dot imports (revive)
  Warning: dot-imports: should not use dot imports (revive)
  Warning: dot-imports: should not use dot imports (revive)
  Warning: dot-imports: should not use dot imports (revive)
  Warning: dot-imports: should not use dot imports (revive)
  Warning: dot-imports: should not use dot imports (revive)
  
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
  
  Error: golangci-lint exit with code 4
  ```

**Comment by artek-koltun** [comment]
hmmm... we do not return an error from `opi-test` container if any dependent job failed
https://github.com/opiproject/godpu/actions/runs/6624028934/job/17992191583?pr=347#step:9:69

**Comment by brianroch** [comment]
Thanks @glimchb, @artek-koltun. I think the `nolint` sections over the dot imports are more tolerable than pre-pending all functions with `gingko.`. I would go with the fix that you have included.

**Review by glimchb — APPROVED** [review]

**Comment by glimchb** [comment]
> Thanks @glimchb, @artek-koltun. I think the `nolint` sections over the dot imports are more tolerable than pre-pending all functions with `gingko.`. I would go with the fix that you have included.

thanks

**Pull request merged**
